BaseURL: "http://vidhance.com"
languageCode: "en-us"
title: "Vidhance"
blackfriday:
  extensions:
    - hardLineBreak
theme: hugo-vidhance-theme
MetaDataFormat: "yaml"
menu:
  main:
    - name: "News"
      weight: 15
      URL: "/newspost/"
